In [1]:
# 경고 메시지가 안나오게..
import warnings
warnings.filterwarnings('ignore')

# 기본
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

# KFold
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 교차 검증 함수
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate

# 학습 데이터와 검증데이터로 나누는 함수
from sklearn.model_selection import train_test_split

# 데이터 전처리
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 하이퍼 파라미터 튜닝
from sklearn.model_selection import GridSearchCV

# 평가함수
from sklearn.metrics import accuracy_score

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor

# 군집
from sklearn.cluster import KMeans
from sklearn.cluster import MeanShift

# 차원축소
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# 딥러닝
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf

# 저장
import pickle

# 그래프 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['font.size'] = 16
plt.rcParams['figure.figsize'] = 20, 10
plt.rcParams['axes.unicode_minus'] = False

In [2]:
# 준비된 수술 환자 데이터를 가져온다.
# 1이 생존, 0 이 사망
df1 = pd.read_csv('data/ThoraricSurgery.csv')
df1.head()

293  1   3.8   2.8  0  0.1  0.2  0.3  0.4  0.5  12  0.6  0.7  0.8  1.1  \
0    1  2  2.88  2.16  1    0    0    0    1    1  14    0    0    0    1   
1    8  2  3.19  2.50  1    0    0    0    1    0  11    0    0    1    1   
2   14  2  3.98  3.06  2    0    0    0    1    1  14    0    0    0    1   
3   17  2  2.21  1.88  0    0    1    0    0    0  12    0    0    0    1   
4   18  2  2.96  1.67  0    0    0    0    0    0  12    0    0    0    1   

   0.9  62  0.10  
0    0  60     0  
1    0  66     1  
2    0  80     1  
3    0  56     0  
4    0  61     0

In [3]:
# 입력과 결과 데이터로 나눈다.
x = df1.drop('0.10', axis=1)
y = df1['0.10']

display(x)
display(y)

293  1   3.8   2.8  0  0.1  0.2  0.3  0.4  0.5  12  0.6  0.7  0.8  1.1  \
0      1  2  2.88  2.16  1    0    0    0    1    1  14    0    0    0    1   
1      8  2  3.19  2.50  1    0    0    0    1    0  11    0    0    1    1   
2     14  2  3.98  3.06  2    0    0    0    1    1  14    0    0    0    1   
3     17  2  2.21  1.88  0    0    1    0    0    0  12    0    0    0    1   
4     18  2  2.96  1.67  0    0    0    0    0    0  12    0    0    0    1   
..   ... ..   ...   ... ..  ...  ...  ...  ...  ...  ..  ...  ...  ...  ...   
464   98  6  3.04  2.40  2    0    0    0    1    0  11    0    0    0    1   
465  369  6  3.88  2.72  1    0    0    0    1    0  12    0    0    0    1   
466  406  6  5.36  3.96  1    0    0    0    1    0  12    0    0    0    0   
467   25  8  4.32  3.20  0    0    0    0    0    0  11    0    0    0    0   
468  447  8  5.20  4.10  0    0    0    0    0    0  12    0    0    0    0   

     0.9  62  
0      0  60  
1      0  66  
2      0  80  
3      0  56  
4      0  61  
..   ...  ..  
464    0  76  
465    0  77  
466    0  62  
467    0  58  
468    0  49  

[469 rows x 17 columns]

0      0
1      1
2      1
3      0
4      0
      ..
464    0
465    0
466    0
467    1
468    0
Name: 0.10, Length: 469, dtype: int64

In [4]:
# 학습용과 검증용으로 데이터 구분
train_X, test_X, train_y, test_y  = train_test_split(x,y)

In [5]:
# 머신러닝
model1 = LogisticRegression()
model1.fit(train_X,train_y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [6]:
pred1 = model1.predict(test_X)
pred1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [7]:
r1 = accuracy_score(test_y, pred1)
r1

0.8389830508474576

In [8]:
# 딥러닝 구조를 결정한다.
model2 = Sequential()
model2. add(Dense(30, input_dim=17, activation='relu'))
model2.add(Dense(1, activation = 'sigmoid'))

In [10]:
# 딥러닝 실행
model2.compile( loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])
model2. fit(train_X, train_y, epochs=30, batch_size=10)

Epoch 1/30
36/36 [==============================] - 0s 2ms/step - loss: 0.5898 - accuracy: 0.3674
Epoch 2/30
36/36 [==============================] - 0s 2ms/step - loss: 0.1683 - accuracy: 0.8311
Epoch 3/30
36/36 [==============================] - 0s 2ms/step - loss: 0.1719 - accuracy: 0.8259
Epoch 4/30
36/36 [==============================] - 0s 2ms/step - loss: 0.1459 - accuracy: 0.8533
Epoch 5/30
36/36 [==============================] - 0s 2ms/step - loss: 0.1321 - accuracy: 0.8665
Epoch 6/30
36/36 [==============================] - 0s 2ms/step - loss: 0.1697 - accuracy: 0.8305
Epoch 7/30
36/36 [==============================] - 0s 2ms/step - loss: 0.1567 - accuracy: 0.8418
Epoch 8/30
36/36 [==============================] - 0s 2ms/step - loss: 0.1544 - accuracy: 0.8452
Epoch 9/30
36/36 [==============================] - 0s 2ms/step - loss: 0.1596 - accuracy: 0.8384
Epoch 10/30
36/36 [==============================] - 0s 2ms/step - loss: 0.1565 - accuracy: 0.8419
Epoch 11/30
36/36 [

In [11]:
# 예측 결과 추출(예측 결과값이 1일 확률)
pred2 = model2.predict(test_X)
pred2

array([[3.53110835e-07],
       [8.27564719e-08],
       [1.34201400e-04],
       [6.11557240e-08],
       [1.08528603e-02],
       [6.94515333e-02],
       [3.49934481e-07],
       [2.71221157e-02],
       [2.39190506e-03],
       [8.19658786e-02],
       [1.09073915e-06],
       [5.19631198e-04],
       [8.52197118e-05],
       [1.58347305e-07],
       [7.86866844e-02],
       [3.64204682e-02],
       [1.32389702e-02],
       [5.89779520e-05],
       [3.83796714e-06],
       [8.96557367e-07],
       [1.10708292e-07],
       [5.37630467e-06],
       [6.22935593e-02],
       [2.00955881e-04],
       [1.14458896e-01],
       [3.71465688e-07],
       [1.49438472e-06],
       [4.85917628e-02],
       [2.84036068e-04],
       [7.80002811e-05],
       [3.09382286e-02],
       [9.41380222e-06],
       [7.00730481e-04],
       [9.32061747e-02],
       [2.87772028e-09],
       [8.18283581e-07],
       [2.31948942e-02],
       [1.85366625e-05],
       [1.25659969e-10],
       [1.97634722e-06],


In [13]:
# 예측 결과를 생성한다.
result2= (pred2 >= 0.5).astype(int)
result2

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [14]:
r2 = accuracy_score(test_y, result2)
r2

0.8559322033898306