In [1]:
import numpy as np

In [2]:
# 기울기 a와 y 절편 b 
기울기 = 3
y절편 = 76

In [3]:
# 입력과 결과
입력 = [2, 4, 6, 8]
결과 = [81, 93, 91, 97]

In [4]:
# 입력된 값에 따라 결과를 예측하는 함수
def predict(x) :
    return 기울기 * x + y절편

In [5]:
# 예측 결과를 추출한다.
# 예측 결과를 담을 리스트
pred_list= list()

for v1 in 입력 :
    a1 = predict(v1)
    pred_list.append(a1)
    
pred_list

[82, 88, 94, 100]

In [6]:
# 진짜 결과와 예측 결과를 뺀 값을 가져온다.
array1 = np.array(pred_list)
array2 = np.array(결과)

print(array1)
print(array2)


[ 82  88  94 100]
[81 93 91 97]


In [7]:
# 진짜 결과와 예측 결과를 뺀 값을 가져온다.
array3 = array1 - array2
print(array3)

[ 1 -5  3  3]


In [9]:
# 제곱을 구한다.
array4 = array3 **2
print(array4)

[ 1 25  9  9]


In [10]:
# 평균을 구한다.
mse = array4.mean()
print(f'평균 제곱 오차 값 : {mse}')

평균 제곱 오차 값 : 11.0
